# generated by huangwf @ 2021.02.07

cc_binary (
    name = 'test_uniq_id',
    srcs = [
        'cpp_common/demo/test_uniq_id.cpp',
    ],
    deps = [
        '#pthread',
        '//cpp_common:cpp_common',
    ],
)
